version: "3"

services:
  api:
    build: .
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8600:80"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
